select NAME, DISPLACEMENT, NUMGUNS from CLASSES
join SHIPS S on CLASSES.CLASS = S.CLASS
where DISPLACEMENT = (select MIN(DISPLACEMENT) from CLASSES)
  and NUMGUNS = (select MAX(NUMGUNS) from CLASSES where DISPLACEMENT = (select MIN(DISPLACEMENT) from CLASSES));