-- Г)
select STUDIONAME, STARNAME, COUNT(*) from MOVIE M
join STARSIN S on M.TITLE = S.MOVIETITLE and M.YEAR = S.MOVIEYEAR
group by STUDIONAME, STARNAME
having COUNT(*) >= ALL(select COUNT(*) from MOVIE, STARSIN
    where TITLE = MOVIETITLE and YEAR = MOVIEYEAR and STUDIONAME = M.STUDIONAME group by STUDIONAME, STARNAME);
