select STARNAME, TITLE, NAME, NETWORTH from STARSIN
join MOVIE M on STARSIN.MOVIETITLE = M.TITLE and STARSIN.MOVIEYEAR = M.YEAR
join (select CERT, NETWORTH, NAME
      from MOVIEEXEC
      where NETWORTH = (select MAX(NETWORTH) from MOVIEEXEC)) ME on ME.CERT = M.PRODUCERC;