select STUDIO.NAME, MIN(M.YEAR) as FIRST_FILM, MAX(M.YEAR) as LAST_FILM, COUNT(distinct M.TITLE) as TOTAL_FILMS from STUDIO
join MOVIE M on STUDIO.NAME = M.STUDIONAME
where STUDIO.NAME like 'M%'
group by STUDIO.NAME;